---

- name: "Update local composer"
  shell: composer self-update
  connection: local
  become: yes
  become_user: root

- name: "Build project dependencies"
  shell: composer install
  connection: local